### ISSUE TITLE
Tags support

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#116]

**Comment by di72nn** [comment]
* Filter lists by tags.
 * Manage tags (add new).

**Comment by anarcat** [comment]
any progress here? it's quite problematic to have to go back to the web interface to tag articles here... especially since *that* interface isn't particularly streamlined for adding tags. :) (e.g. https://github.com/wallabag/wallabag/issues/2246, https://github.com/wallabag/wallabag/issues/719, https://github.com/wallabag/wallabag/issues/2760, ...)

**Comment by Strubbl** [comment]
@anarcat no, not yet. Maybe you want to help in this issue with a pull request?

**Comment by anarcat** [comment]
unfortunately i can't prioritize this right now, thanks for the offer. :)

**Comment by di72nn** [comment]
Basic tags support is now available in [2.0.0a](https://github.com/wallabag/android-app/releases/tag/2.0.0a).

**Comment by Strubbl** [comment]
@tcitworld @di72nn 
What would be the extended tags support? Or can this issue be closed?

**Comment by di72nn** [comment]
I'll close it. For anything else new "improvement" or "feature" issues can be opened.
