### ISSUE TITLE
[1.9] Can't sync

### ISSUE THREAD

**Issue by khinsen** [wallabag/android-app#118]
I just signed up for the beta testing program and installed the new app. Then I configured it for my Framabag account. Result: "Erreur de traitement du flux" (my phone is configured in French).

Of course I checked all my configuration info (login, password, user ID, token) ten times. I also regenerated a new token and double-checked it. No chance.

In the "settings" dialog, the connection test works fine, but the one for obtaining the RSS info leads to an error message.

**Comment by m-dubois** [comment]
Same for me here, but using my own wallabag server.
Do yo need more infos?

**Comment by m-dubois** [comment]
C'est un peu le m*rdier dans logcat :p
Mais j'ai quand même vu la stack suivante qui pourrit p'têt aider:

```
E/FeedUpdater.updateByF( 2904): XmlPullParserException on Main
E/FeedUpdater.updateByF( 2904): org.xmlpull.v1.XmlPullParserException: expected: START_TAG {null}rss (position:START_TAG <html class='ng-csp' data-placeholder-focus='false' lang='en'>@7:82 in java.io.InputStreamReader@41eaaf78) 
E/FeedUpdater.updateByF( 2904): 	at org.kxml2.io.KXmlParser.require(KXmlParser.java:2056)
E/FeedUpdater.updateByF( 2904): 	at fr.gaulupeau.apps.Poche.network.tasks.FeedUpdater.processFeed(FeedUpdater.java:226)
E/FeedUpdater.updateByF( 2904): 	at fr.gaulupeau.apps.Poche.network.tasks.FeedUpdater.updateByFeed(FeedUpdater.java:173)
E/FeedUpdater.updateByF( 2904): 	at fr.gaulupeau.apps.Poche.network.tasks.FeedUpdater.updateAllFeeds(FeedUpdater.java:107)
E/FeedUpdater.updateByF( 2904): 	at fr.gaulupeau.apps.Poche.network.tasks.FeedUpdater.doInBackground(FeedUpdater.java:71)
E/FeedUpdater.updateByF( 2904): 	at fr.gaulupeau.apps.Poche.network.tasks.FeedUpdater.doInBackground(FeedUpdater.java:30)
E/FeedUpdater.updateByF( 2904): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/FeedUpdater.updateByF( 2904): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/FeedUpdater.updateByF( 2904): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/FeedUpdater.updateByF( 2904): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/FeedUpdater.updateByF( 2904): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/FeedUpdater.updateByF( 2904): 	at java.lang.Thread.run(Thread.java:841)

```

**Comment by tcitworld** [comment]
Can you provide your rss feeds to test which entry is the one that causes the failure ?

**Comment by di72nn** [comment]
It looks like there is HTML instead of XML-feed which usually means wrong "User ID" or "Feed Token".

Have you tried using "Get feeds credentials" ("Obtenir les informations du flux RSS") button in settings? Try it, if you haven't.

**Comment by m-dubois** [comment]
Good point ! When I try "Get feeds credentials", I have the message "Can't find the credentials" (translated from french :p)

and in the log:

```
D/WallabagService( 2904): executeRequest() start; autoRelogin: true
D/WallabagService( 2904): executeRequest() got response
D/WallabagService( 2904): getGenerateTokenRequest() url: https://mydomain/owncloud/?feed&action=generate
D/WallabagService( 2904): executeRequest() start; autoRelogin: true
D/WallabagService( 2904): executeRequest() got response
D/WallabagService( 2904): executeRequest() start; autoRelogin: true
D/WallabagService( 2904): executeRequest() got response
```
I'm gonna check my credentials, token, ... 

The "Test connection" button only checks the connection to the server then? Not the connection with id password?

**Comment by tcitworld** [comment]
If the user ID or token is wrong, wallabag sends a plain text file, not HTML, so it's really an entry causing the problem.

**Comment by m-dubois** [comment]
The user id and the token are the one given by the app (on a desktop).
There's maybe something else... I noticed that in the app, my url is:

https://mydomain.ext/OWNCLOUD !!!! WHAAAAAAAAAAAT?

well... :)
So, I changed it to the right one, and still an error (see log below) :/

(I first wanted to say that the www. alias was added in the website, whereas in the app, it generated an error... but now that I changed it with the right context url, it's ok)

-- 
I resume:
- I had a connection check: ok but credentials check: bad
(the owncloud url was a good url, so connection check was 'normal')
- I checked my user id and token: good
- I had a bad context url (owncloud instead of wallabag)
- fixed it: still an error
- in my wallabag website, when I logged in with url https://mydomain.ext/wallabag, I was redirected to https://www.mydomain.ext/wallabag (notice the www. prefix added)
- in the app, I had https://mydomain.ext/wallabag
- changed it to https://www.mydomain.ext/wallabag
- tadaaaaaaa! everything is working !

well, now the problem is that it might not be the same problem than @khinsen :/
I hope I did not hijacked your issue :-/

**Comment by khinsen** [comment]
@tcitworld What exactly do you need to test my RSS feed(s) ?

**Comment by m-dubois** [comment]
@khinsen You can install aLogcat (available on f-droid and google playstore - if you use the latter) and you will find the log (among a lot of other messages)

In the configuration of the wallabag webapp, you can get the url of your feeds (unread, favorites, archives)

In my case, I had a problem at @7:82, so I check the lines and columns to see what was wrong (but actually, the problem was elsewhere :))

**Comment by khinsen** [comment]
I had a look at the system logs (WallabagService). I can't make much of what I see there, but there is a URL that apparently is looked up to get the feed credentials:

  http://www.framabag.org/?feed&action=generate

Pasting that URL into Firefox yields the Framabag Web site, so perhaps this is related to my problem?

**Comment by nicosomb** [comment]
Did you already generate Token for your RSS feeds? via config page

**Comment by m-dubois** [comment]
Maybe... the gurus will tell :)
But no user id / password is asked... we get the 200 response right away... maybe that if the request contains thoses fields, it logs you and gives you the rss feeds... I have no clue about that...

**Comment by m-dubois** [comment]
He first wrote:
```
Of course I checked all my configuration info (login, password, user ID, token) ten times. I also regenerated a new token and double-checked it. No chance.
```
So I guess it's ok

**Comment by di72nn** [comment]
Isn't framabag URL supposed to have something like "/u/username" in it?

**Comment by khinsen** [comment]
If I use Framabag on the Web, yes, there is a /u/username part. Since the examples given in the Android app do not contain it, I supposed that this is appended automatically.

I tried adding this, and it works! So I guess this issue can be closed. However, some documentation somewhere should say what exactly the URL for a Wallabag instance is. I understand that the Android app is not the right place. My suggestion would be that Wallabag (the Web server) should show the URL for syncing explicitly on the config page, along with the user ID and token.
