### ISSUE TITLE
Tapping on links no longer brings up menu

### ISSUE THREAD

**Issue by nwa573** [wallabag/android-app#1184]
In the past, when I tapped a link in an article, it brought up a menu with options like adding the URL to wallabag, viewing it in a browser, etc.  In the most recent update on my tablet, wallabag now just immediately tries to open the URL in the same window.  

# Environment details
- **wallabag app version**: 2.4.3 (229)
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Google Play
- **Android OS version**: 6.0.1
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock
- **Android hardware**: Nexus 7
- **wallabag server version**: wallabag.it

This doesn't happen when I use wallabag on my Android 10 phone, so I'm guessing it's a bug related to my tablet only being able to run old versions of Android.  I'm not sure if it's worth fixing but thought I would report it in case it's an easy fix.  Thanks so much for the app!

**Comment by di72nn** [comment]
> so I'm guessing it's a bug related to my tablet only being able to run old versions of Android. I'm not sure if it's worth fixing but thought I would report it in case it's an easy fix.

Things like that should definitely be reported. Thanks for doing so!

**Comment by AnneLaureF** [comment]
I noticed the same thing on my.phone and it's bugging me because I only have spotty 3G right now so I definitely don't want to open the URL.
   * wallabag app version: 2.4.3 (229)
   * wallabag app installation source (e.g. Gplay, F-Droid, manual): F-Droid
   * Android OS version: 6.0
   * Android ROM (e.g. stock, LineageOS, SlimRom,…): stock
   * Android hardware: Wiko U Feel
   * wallabag server version: wallabag.it

however it still works as expected on my tablet running a newer version of Android
   * wallabag app version: 2.4.3 (229)
   * wallabag app installation source (e.g. Gplay, F-Droid, manual): F-Droid
   * Android OS version: 9
   * Android ROM (e.g. stock, LineageOS, SlimRom,…): stock
   * Android hardware: Galaxy Tab S5e
   * wallabag server version: wallabag.it

I hope it's an easy fix 😉 

Thanks for the otherwise great app
