### ISSUE TITLE
Synchronize don't "push" the "mark as read" article

### ISSUE THREAD

**Issue by pieplu** [wallabag/android-app#145]
Hello,

I use framabag, and this android app.

I can synchronize article from framabag, but when I "mark as read" an article on my phone,
the article stay as unread on my framabag.

Thanks!

**Comment by di72nn** [comment]
Hello,

Unfortunately, current "synchronization" is only one-way sync (server -> client). Full synchronization is not planned until version 2.* (because of the lack of server-side API in 1.9.*).

You may want to try (if you didn't try it yet) [beta version](https://play.google.com/apps/testing/fr.gaulupeau.apps.InThePoche), which pushes such changes at the moment you press "mark as read" / "add to favorites" / "delete" button on an article (however, if you are offline, the article state won't be pushed to a server (neither at that moment or later)).

**Comment by tcitworld** [comment]
@pieplu New version is now available at Google Play and F-Droid, did you have a look at it ?

**Comment by pieplu** [comment]
@tcitworld I see it!

Thanks! Now I can convert a friend :)

**Comment by tcitworld** [comment]
:)
