### ISSUE TITLE
java.security.cert.CertPathValidatorExc Anchor not found

### ISSUE THREAD

**Issue by nicosomb** [wallabag/android-app#151]
Found on Google Play 

> Neue Version akzeptiert SSL Zertifikat nicht mehr Die neue Version akzeptiert mein SSL Zertifikat nicht mehr. Mit der alten ging das ohne Probleme. java.security.cert.CertPathValidatorExc Anchor not found

**Comment by tcitworld** [comment]
Can we contact him ? There's an option in the settings panel. Maybe we can handle the exception and display a message warning ? cc @di72nn

**Comment by nicosomb** [comment]
I can't find his email

**Comment by di72nn** [comment]
I'm not sure about all of this.
I didn't write any "accept all SSL certs" code, I only wrapped it in "if" block (yes, it was *always on* before). In the PR above I rolled back one change in the code, that might cause the error (I have no idea, actually).
I strongly suggest doing something like [this](https://davdroid.bitfire.at/faq/entry/importing-a-certificate) instead of accepting any SSL certificates.
