### ISSUE TITLE
URL issue with badly processed wallabag links

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#187]
I added a link to wallabag as text (starting directly with domain name, eg _boingboing.net_) through the android app and therefore the URL was saved as so. 
When it got synced back to the app the domain shown on unread panel wasn't filtered to domain name, and the menu item or the link on top of the article to go to original URL led to NULL, and therefore crashed the app when followed.

TODO : Even if it's also a server issue, fix domain filtering [here](https://github.com/wallabag/android-app/blob/master/app/src/main/java/fr/gaulupeau/apps/Poche/data/ListAdapter.java#L72) and [there](https://github.com/wallabag/android-app/blob/master/app/src/main/java/fr/gaulupeau/apps/Poche/data/ListAdapter.java#L72) in that case (add the `http://` part if needed). 
Also, when sending URL, be sure that's it's a correct URL (I don't know how wallabag v2 handles this kind of things).

**Comment by Strubbl** [comment]
I think we should rely on the server here. It does not make sense to double that logic from server also in the app.

I think this issue can be closed, because wallabag v2.2.3 does not allow to add an URL without the http:// in front anymore. But i do not know yet, how the API of wallabag behaves in that case. Maybe that still allows URLs without http:// ?

**Comment by Strubbl** [comment]
I just reproduced your issue by adding boingboing.net via app as article. In wallabag web exactly this URL is show. 

I do not what exactly fixed this, but it is not reproducible anymore. I can open the original url via menu, also opening the link on top of the article worked.

**Comment by di72nn** [comment]
Not an issue anymore?
