### ISSUE TITLE
offline mode

### ISSUE THREAD

**Issue by foxmask** [wallabag/android-app#246]
Proposal of the day ;)  offline mode
- What's happen when internet connection is lost

we cant do anything as any action need to be synchronized once we have deleted or marked as read , etc.
- What could be done to fix it for a better ux

So it would be helpful if wallabag stores the history of actions we made locally, and then, plays the history, once the internet comes back to.
- a bit further

For each tag, a parameter could permit to use offline mode To avoid to consume too many space on our mobile / too many data in our mobile carrier subscription
For post without tag, a default behavior should be adopted.

**Comment by Strubbl** [comment]
i would love to see offline mode in Wallabag Android app. Before i used Pocket. And it used 1 GB space in my device. But it had offline mode support. At the moment my Wallabag app uses 22 MB with approx the same amount of articles (~800). 

In Wallabag Android i would go the same approach. All articles completely offline or none. Otherwise software is getting too complex. 

As next steps in offline mode i would see saving images offline. And then saving actions (fav, archive, delete) offline to sync when internet has come back. Maybe a switch in the settings "sync only when Wifi connection and not on mobile data" makes sense then.

**Comment by foxmask** [comment]
Agreed

**Comment by prysme01** [comment]
yes please add an offline mode, I would love to read my "poched" articles without data connection.

**Comment by tcitworld** [comment]
See https://github.com/wallabag/android-app/pull/282 which is a work in progress.

**Comment by prysme01** [comment]
Great thank you !

**Comment by anarcat** [comment]
with #282 committed - is this complete?

**Comment by di72nn** [comment]
Done. See also #361.
