### ISSUE TITLE
Android application crash when refreshing

### ISSUE THREAD

**Issue by foxmask** [wallabag/android-app#251]
Je vais le faire un français parce-que en anglais ça va pas le faire ;)

Quand on rafraîchit avec le bouton à droite du plus on plante tout le temps l'application
Quand on rafraîchit en tirant la liste vers le bas, tout va bien

J'utilise Android 6 sur nexus 5

**Comment by di72nn** [comment]
If you update using "Update all feeds" from menu, the app performs clean update of all the lists (yeah, that's takes some time).
If you use pull-to-refresh, the app only updates selected list (also, for the main list it only downloads new articles - that's why it usually very fast).

It's probably not documented anywhere.

**Comment by cortexx** [comment]
Ok same problem here, with App in 1.9.9.3 version on CyanogenMod version 12.1 and Android 5.1.1.
Thanks @di72nn for the tip with the pull-to-refresh method, the sync is OK now but it's impossible to use the update-all-feeds method.

**Comment by foxmask** [comment]
in fact the pull-to-refresh, add new items but does not remove existing that I removed on the web instance for example... so until this is fixed I unable to use the app, deleting the item twice ; one one the web instance one in the mobile app is too anoying as I get most of 100 items/day, that I almost removed once I read them the same day.

**Comment by zertrin** [comment]
Same here. I just migrated from my self hosted v1.9.1 to v2.0.4. As for the android app, I uninstalled it and reinstalled it (before and after was v1.9.9.3) to make sure the database was wiped. 

I could successfully login with the app but the refreshing of the database through the popup crashes the app. Using the refresh icon on the top right does the same (app crash).

After reading this thread I tried pull-to-refresh which did work. However I'm afraid that as foxmask stated above this is not really a solution as the items removed from the server won't be removed in the app...

Additionnaly I would like to add that I think that a variant of this issue was present when using wallabag v1.9.1 before. The app was not crashing when updating-all-feeds but the update didn't work as expected either (no removal of items that were removed from the server). With pull-to-refresh, I could get the new items. However I can't be sure that this was directly related to this issue.

Is there another way to help you debugging this issue? (is there any form of debug mode?)

**Comment by Strubbl** [comment]
Since you are now using Wallabag v2 you can set the limit of items in your RSS feed (in Wallabag -> Configuration -> RSS -> Number of items in feed). 

To help you could build the app from this repository and install the debug version to your device. Then you have access to logcat.

Did you install via Play store? Then you can also help with sending the crash report when Android asks you for permission.

Hopefully, @tcitworld is releasing a new App version soon with you please check again for the crash. There were several issues fixed recently.

**Comment by di72nn** [comment]
Can someone reproduce the crash with the latest client version (1.10)?

The fact that pull-to-refresh does not delete articles is expected behavior - it is the price for fast updates (probably won't be fixed until the app migrates to v2 API).

**Comment by foxmask** [comment]
I dont with 1.10 nor the previous one
