### ISSUE TITLE
Add as an 'Open With' Target

### ISSUE THREAD

**Issue by jalcine** [wallabag/android-app#252]
Currently, my workflow for Wallabag is as follows:

 * Open link in email/app/etc
 * Navigate to said link in web browser
 * Share link from web browser to wallabag

This is a request/ideation to have Wallabag register itself as a Web browser (or at least a handler of HTTP links) so that the loop from app -> browser -> wallabag can be shortened (i.e. middle man being removed).

**Comment by tcitworld** [comment]
Not sure if this is right. It's more like an android or app issue. For instance, my mail app (K9-Mail) allows to long press on link in order to share it.
Also, you'll need to choose your browser each time you'll open a regular link (that you just want to view) if you want to have the option to use wallabag like this.

**Comment by di72nn** [comment]
I actually implemented handling of HTTP scheme recently.
I do agree that it's probably the email/whatever app issue, but sometimes the feature may be handy.

**Comment by jalcine** [comment]
@tcitworld: I see. I personally have no problem with this (as I have > 5 browsers on my phone and tablet - webdev life :grin:).

**Comment by jalcine** [comment]
@di72nn: I think I'll take @tcitworld's advice and go down the long-press -> share approach.
Thanks for that tip!
