### ISSUE TITLE
Export in EPUB format

### ISSUE THREAD

**Issue by Ygster** [wallabag/android-app#286]
Now it is possible to download each article only in PDF format, but in the web app the EPUB format is available too.
It would be interesting to have this format in the android app. #

**Comment by Strubbl** [comment]
We should remove the export to pdf option menu entry and add a more generic export entry. After clicking on this export menu it should show a fragment where we can choose the format.

Is it possible to get the allowed export types from the wallabag instance via API?
Otherwise a hack would be to login to the instance as the user and get the HTML view of an article, regex out all allowed formats and display them.

**Comment by tcitworld** [comment]
> Otherwise a hack would be to login to the instance as the user and get the HTML view of an article, regex out all allowed formats and display them.

Nope nope nope nope. IIRC, the API should now expose all the available formats : https://app.wallabag.it/api/doc#get--api-entries-{entry}-export.{_format}

**Comment by di72nn** [comment]
The code to download all the formats via API is there, it just a matter of passing an appropriate parameter to [this method](https://github.com/wallabag/android-app/blob/master/app/src/main/java/fr/gaulupeau/apps/Poche/service/ServiceHelper.java#L159).

There is a fallback for older servers that should work for most of the formats (I think). Errors in this case are tolerable in my opinion.

**Comment by Strubbl** [comment]
threatening with evil regex hacks sometimes works to push an issue 👍 😆
