### ISSUE TITLE
Show estimated reading time

### ISSUE THREAD

**Issue by fantasio31** [wallabag/android-app#358]
It should be great to have information of estimate reading time for each article.

Estimate reading time is particularly interesting on Smartphone as articles can be read in a bus, in the metro or in a plane, where travel time is very different.

This information is displayed in web interface of Wallabag (actually Wallabag v1 which is my instance, i don't know for wallabag v2) but i have not been able to find it in Android app.

**Comment by ngosang** [comment]
I think this feature is already implemented.

**Comment by di72nn** [comment]
Currently it is a hack implemented in wallabag v2 RSS feeds (current version of the app uses RSS feeds). The feature is not present (and it will never be implemented) for wallabag v1.9.

But when we move to v2 API (as apposed to RSS feeds) we will need to implement it in the app. The issue is not obvious, but valid.

**Comment by di72nn** [comment]
Done.
