### ISSUE TITLE
[Feature request] Use QR codes to set the mobile applications up

### ISSUE THREAD

**Issue by nicosomb** [wallabag/android-app#4]
Adding the id and token manually to the application was a bit frustrating. It would be great if we could just generate a QR code from the settings that the mobile application could scan to fill the fields up.

See https://github.com/wallabag/wallabag/issues/432

**Comment by blitzmohit** [comment]
I was looking at implementing this in the application. I wanted to know how you would prefer it :
1) Explicit Intent to let the user handle the scanning part similar to what Google Authenticator uses.
2) Implicit Intent and adding a scanning library to the codebase to handle it.

**Comment by tcitworld** [comment]
We should have a look on how other Floss apps handle this.

**Comment by tcitworld** [comment]
Not really needed for wallabag v2... However.

**Comment by Strubbl** [comment]
if you give user name and password, you can retrieve the id and token by pressing the button in the settings (retrieve feed access data). 

This ticket is obsolete, isn't it?

**Comment by azrdev** [comment]
Especially when using an own server, it would be useful to scan a QR-code on the config page instead of having to type URL, username, and password.

**Comment by di72nn** [comment]
Since #290 we can fill in URL and username using `wallabag://` scheme, which can be received from an external QR-code scanner. For example, you can scan the following QR-code using [Barcode scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android):
![wallabag://user1@wallabag.example.com](https://chart.googleapis.com/chart?cht=qr&chl=wallabag%3A%2F%2Fuser1%40wallabag.example.com&chs=180x180&choe=UTF-8&chld=L|2)
(QR code text: `wallabag://user1@wallabag.example.com`).
If you "open" the URL, the wallabag app will open connection wizard with URL and username filled in - you only need to enter password and press "next".

**Barcode generation is not implemented on the server side**, though.

**Comment by Strubbl** [comment]
Since i could not find an issue for the QR Code stuff on server side, i created one and hope that it is okay: https://github.com/wallabag/wallabag/issues/2448

**Comment by nicosomb** [comment]
See https://github.com/wallabag/wallabag/pull/2523

**Comment by anarcat** [comment]
looks like the server-side API changes are here: https://github.com/wallabag/wallabag/pull/2523 we just need to scan stuff now...

**Comment by nicosomb** [comment]
Thank you 👍

**Comment by anarcat** [comment]
@nicosomb hmm... that's just the wallabag side - i didn't see a scanner on the android app side, are you sure this is completed?

**Comment by nicosomb** [comment]
yes it is 👍  see https://github.com/wallabag/android-app/pull/300

**Comment by anarcat** [comment]
uh! that's cool i guess... how does it work? is the user expected to fire up a barcode scanner on his/her own?

because i didn't see a "scan" button during configuration... maybe some shortcut would be helpful...

**Comment by nicosomb** [comment]
On your web app, you need to scan the QR code, then the android app will be opened with some of your settings.

**Comment by di72nn** [comment]
@anarcat yeah, I added #362 today.

**Comment by anarcat** [comment]
@di72nn right, thanks!
