### ISSUE TITLE
Synchronization with server not working

### ISSUE THREAD

**Issue by bnjbvr** [wallabag/android-app#428]
Sorry because this issue will be vague, but I don't know how to find logs for the Android app?

I've checked all the checkboxes in the Android app for live synchronization between my local list on Android and the server. However, after marking an article as read in the Android app, it never gets sync'ed to the server, even after more than 12 hours. (I've set the synchronization to happen at least every other 12 hours, in "full mode" because this sounded safer)

Is there something I'm missing here?

**Comment by di72nn** [comment]
There's no difference between synchronization types (fast/full) in regard of client->server sync (it only matters for server->client update).

If there is no internet connection, the app may silently skip scheduled synchronization.

First of all, you may anytime check whether the app has any unsync'ed changes: if there are unsync'ed changes, "Sync local changes" option in the menu of the main activity (the one with lists) will be available (otherwise the option is hidden). If you press it, it should either sync changes or show an error message.

If you can't see the option (no unsync'ed changes), but you're sure that some changes were not sync'ed. We need to investigate sync process.

If you can see the option (after a significant period of time passed since the actual change), the auto-sync probably didn't work (presumably because of lack of internet connection at the moment of scheduled sync).

So let's start with finding the menu option (and pressing it, if it is present).

**Comment by di72nn** [comment]
Stale.
