### ISSUE TITLE
Has Framabag support been permanently dropped?

### ISSUE THREAD

**Issue by Lokesh-Krishna** [wallabag/android-app#481]
I know that Wallabag isn't responsible for Framabag not updating to the latest version but is there anything that Wallabag can do to get Framabag to update?

I am unable to see any options to contact the Framabag team on their website and I was wondering if members of the Wallabag team could contact them and request them to update. It remains the easiest method to start using Wallabag. 

I know that this doesn't qualify as an issue in the usual sense but I wanted to discuss it with y'all and this felt like the best way to do that.

**Comment by nicosomb** [comment]
Hello @Lokesh-Krishna. 

Framabag will be upgraded. When? When it will be upgraded 😉
To contact Frama* teams, you can have a look here: https://contact.framasoft.org/

Have a nice day.

**Comment by tcitworld** [comment]
I'm basically the whole Framabag team as part of Framasoft. We've had other priorities in the last months but it seems we'll have to handle the migration soon since the latest builds of this app don't support wallabag v1 anymore.

Please keep in mind that there's 12k users on Framabag, all of them with a SQLite database which has issues supporting utf8 and this will take a long time to do.

**Comment by Lokesh-Krishna** [comment]
@tcitworld Would it be possible to ask all users of Framabag to export their articles and then you update to v2 without having to worry about the articles and then the users import the articles again? 

I'm sorry if I'm missing something obvious. If this could expedite the process though, isn't it worth considering?

**Comment by tcitworld** [comment]
Talked with others at Framasoft we agreed to make the migration soon.

We plan to have some limitations on it for Framabag to be a service to **discover** wallabag, not a service like wallabag.it.
Therefore, Framabag would have limitations such as the number of articles, or the asynchronous tasks (for big imports) disabled. That's why it wouldn't be possible to import articles *afterwards* migration.
I'll know more about it in a few days.

**Comment by Lokesh-Krishna** [comment]
@tcitworld You mentioned knowing more about this in a few days. Any updates?  
How much would the limit on the articles be? And would users be notified when the migration has been completed? I miss Wallabag a lot.

**Comment by Lokesh-Krishna** [comment]
@tcitworld I don't mean to spam but any update regarding this?

**Comment by tcitworld** [comment]
Yup, sorry, we had to deal with mastodon stuff so this has been postponed. Making a new instance now, will migrate most of the accounts this week or so, so we should be good by the end of the month.

**Comment by Lokesh-Krishna** [comment]
Yay! Thanks so much for replying and for the good news :)

**Comment by tcitworld** [comment]
Planned for tomorrow.
