### ISSUE TITLE
SSL certificat error with Let Encrypt - WB v2 alpha

### ISSUE THREAD

**Issue by DoumeDuSud** [wallabag/android-app#516]
Hello

This V2 look great with the gestion of tag :+1: 

I notice 1 trouble When I want to connect in https with my lets encrypt certificate I have

`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found`

I notice the same error on the master version of Wallabag but I can by pass the certificat validation that I cannot do in the V2 alpha version

My firefox/chronium navigator have no trouble with the certificat for my sub domain (subdom.domaine.tld)

LineageOS 7.1.1 instance Wallabag 2.2.2

**Comment by di72nn** [comment]
Can you check your server with something like [this](https://www.ssllabs.com/ssltest/) and check "Certification Paths" in the results? Every entry should be either "Sent by server" or "In trust store".

There is a bunch of reasons why that exception could happen:
 * The server is not configuration to provide intermediate certificates / not all certification chains provided.
 * Your Android system doesn't have necessary root CA's.
 * Some other reasons.

**Comment by DoumeDuSud** [comment]
I have extra download also : 

![](https://framapic.org/WPma5HOJ0AUk/96lOExmUCZIz)

you need more information ?

![](https://framapic.org/trsCOYiDx9OB/0exGOJDNjJua)

**Comment by di72nn** [comment]
You need to add [Let’s Encrypt Authority X3](https://letsencrypt.org/certificates/#intermediate-certificates) intermediate certificates ([pem](https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem)/[txt](https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt)) either to your certificate file or by specifying it in the web server config, so that "Extra download" turn into "Sent by server".

You can search something like "let's encrypt intermediate certificate setup".

**Comment by di72nn** [comment]
Reopen if you need further assistance.

**Comment by ippocratis** [comment]
Maybe this?
https://github.com/wallabag/android-app/issues/516#issuecomment-298114568
