### ISSUE TITLE
Article's title set twice

### ISSUE THREAD

**Issue by Simounet** [wallabag/android-app#536]
Hi there,
Since #503 I've got the title set twice when sharing an article to Diaspora Native WebApp. This app use EXTRA_TEXT and EXTRA_SUBJECT. I look how Firefox for Android handle this: https://github.com/mozilla/gecko-dev/blob/1a0d9545b9805f50a70de703a3c04fc0d22e3839/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java#L3624-L3627

**Comment by di72nn** [comment]
So Firefox sets title to both `EXTRA_SUBJECT` and `EXTRA_TITLE`, and URL to `EXTRA_TEXT`.

Have you tried sharing from Firefox to various apps?

**Comment by Simounet** [comment]
Yep and it seems to work pretty well.

**Comment by di72nn** [comment]
Putting title as some other `EXTRA` (rather than appending to `EXTRA_TEXT`) makes sense: receiving apps should be able to handle it themselves.

However, according to the docs `EXTRA_TITLE` is used for `ACTION_CHOOSER`, so it might not help.

So, basically it is either 1) add all info separately, but some apps will ignore title, or 2) include title in `EXTRA_TEXT`, but some apps will add title twice.

**Comment by Simounet** [comment]
I prefer the first option. We have to tell people making app wrong they have to fix something instead of making the good ones bad.

**Comment by tcitworld** [comment]
Will test the PR with a few apps.

**Comment by Strubbl** [comment]
@tcitworld did you already have a chance to test this?
