### ISSUE TITLE
Support for ebook reader (i.e. Sony PRS T1)

### ISSUE THREAD

**Issue by franek** [wallabag/android-app#60]
I've got an old ebook reader (Sony PRS T1) which is running Android.
I have succeeded in installing wallabag on my ebook and have synchronized my contents with my own installation of Wallabag. Unfortunately, the app does not handle physical button and.pagination is not smooth. It is not usable with my reader.

Do you know a compatible ebook reader with wallabag ? 

thanks,
Happy new year,

**Comment by tcitworld** [comment]
In fact any RSS feed reader app should do the thing (the wallabag app basically does just this).

**Comment by franek** [comment]
thanks for your answer. Good to know. However I would like to be able to mark as read article through my ebook reader. Otherwise I need to connect to wallabag to "mark as read" articles I have read. It is already what I am doing (I am exporting my reading list by calibre) but I would like to simplify this task. 

Wallabag app would be nice for that.

thanks,

**Comment by tcitworld** [comment]
Well, the sync of "read" articles actually doesn't work (yet...) between the Android app and the wallabag server. We need an API to do this (I have the feeling this is what I'm saying everyday... We really need this ;) ).

**Comment by tcitworld** [comment]
@kevmeyer @shtrom @sinisterstuf @manisman Any idea how it could be possible to « handle physical buttons » ?

**Comment by shtrom** [comment]
The nook has two side buttons (essentially up/down). They already work with the app.

**Comment by tcitworld** [comment]
Yeah, it seems it's a specific problem to your device, @franek.

**Comment by anarcat** [comment]
I have a Kobo e-reader, and this would be a killer feature for me. Right now I need to go through Calibre to export articles and it's really a pain in the butt, as the export is now 1000 pages long, and Calibre painfully regenerates *all* of it everytime, which takes over 10 minutes. Pocket's (and hopefully wallabag's?) model is much better as it allows for syncing articles instead of downloading them all.

As for marking as read, the Kobo readers don't have physical buttons: you would need to track which page the e-reader is at.

**Comment by tcitworld** [comment]
The API allows this. Works just need to be done. :-\

**Comment by tcitworld** [comment]
Thank you for your input.

**Comment by anarcat** [comment]
So you mean to say the Android app itself doesn't do this directly either? So that's one problem that can be fixed on the Android app.

But E-Readers don't all run Android... In the case of the Kobo, while it's possible to install Android on it, i do not think it is running Android by default. It is unclear to me *what* exactly is runing on the thing, but it is clearly running some version of Linux, and we can install apps pretty easily through the SD card so it shouldn't be too hard to deploy an app for Wallabag there, if we figure out what makes it tick.

**Comment by anarcat** [comment]
I posted this on the Mobileread forums to see if it can gain some traction:

http://www.mobileread.com/forums/showthread.php?p=3291461

It seems like the most promising approach is through [KOreader](https://github.com/koreader/koreader/wiki), either through a plugin or [OPDS support](https://en.wikipedia.org/wiki/OPDS)?

**Comment by anarcat** [comment]
OPDS support seems easier, actually - one would just have to implement [support on the server](https://github.com/wallabag/wallabag/issues/1253).

**Comment by di72nn** [comment]
Nothing specific / not related to the Android app.

**Comment by anarcat** [comment]
true that. for the record, i now have a Kobo reader and was able to hack Wallabag support into it with [Wallabako](https://gitlab.com/anarcat/wallabako/). If you have root on your Sony, it *may* be possible to port that software there...
