### ISSUE TITLE
Tag right after share

### ISSUE THREAD

**Issue by nr458h** [wallabag/android-app#675]
If I add a article via the share-menu for example within the browser, it would be helpful to tag the article without leaving the browser

**Comment by roukydesbois** [comment]
Hello,

I'd like to add some details on this: I think it would be useful to, indeed, allow to tag an article when you add it to wallabag, and also to mark it as read directly. 
Functionnally, using the Android "Share to" could open an intermediary page or popup, allowing to add tags and to mark the article as read, and to add to wallabag once this is done.

My use case is that I'm using Wallabag both as a way to be able to read articles offline (the current app does this perfectly), but also as a kind of library, to be able to go back to the article if I'm ever to search for a particular subject. Therefore I don't necessarily need to read the article right away (hence the mark as read), and it is important for me to be able to tag the article when I have it under my eyes rather than after I finish browsing my RSS feed (hence the tag while sharing/adding feature).

Thanks!

**Comment by aemaeth2501** [comment]
+1 Pocket does have a pretty useful mechanism for such feature.
The aim would be to minimize clicks required ;)

**Comment by mneuschaefer** [comment]
+1 When I save a lot of articles, later retrieval is faster when they are tagged at once.

**Comment by nr458h** [comment]
Many thanks @di72nn ! This is awesome - can't wait for the next release.

🎉🎉🎉
