### ISSUE TITLE
TTS - Voice stops as soon as screen is OFF

### ISSUE THREAD

**Issue by waluwaz** [wallabag/android-app#792]
# Issue details

### Actual behaviour
If I click the ON/OFF switch shortly to turn OFF the screen, the voice stops immediately. 

### Expected behaviour
Just as when listening to podcasts, I would expect the voice to keep playing.

# Steps to reproduce the issue
1. Start Wallabag
2. Click an article
3. Turn ON Text to Speech
4. Hit Play
5. Enjoy :-) So far so good.
6. Hit ON/OFF to switch the screen OFF
7. Notice that the voice stops. However, the phone plays some notification sound repeatedly, as if Wallabag was warnin that it's not happy ?!? I haven't noticed that behaviour with any other app.

# Environment details
- **wallabag app version**: 2.2.1
- **wallabag app installation source** : Aptoide
- **Android OS version**: 8.0.0
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): Huawei stock. Google Play disabled.
- **Android hardware**: Huawei Mate 9
- **wallabag server version**: walabag.it
- **Do you have Two-Factor-Authentication enabled?**: no

# Your experience with wallabag Android app
I dislike that it turns off when the screen is off. But I was very impressed by the TTS feature, the fact that the voice resynchonizes if I scroll in the text, the fact that just as for podcasts, the app will bring me back to the right part of the text. Thank you for this nice project.

**Comment by Strubbl** [comment]
ping @tyndare 
can you please have a look at this issue?

**Comment by tyndare** [comment]
Playback should have continued even with screen turned off.
I initially suspected an aggressive power saving mode but the warning notification sound you mention looks like a bug or permission issue.
Does the application continue playback if you just click the home button to put it in the background ?

I haven't found Wallabag 2.2.1 on Aptoide, I only found Wallabag 2.0.2 which had indeed some background playback issue.

Could you try installing the latest Wallabag from F-Droid (https://f-droid.org/) or the github release page (https://github.com/wallabag/android-app/releases) instead of Aptoide ?

**Comment by waluwaz** [comment]
The app was definitely 2.2.1 as confirmed by the about section of the app. It may have come from fdroid from the beginning.

Anyway, I redownloaded from the fdroid website and «updated» the app to 2.2.1.

I have the same behaviour before and after the «update». I have similar behaviour with the on/off switch or with the home button. In both case, I hear a notification sound. With the home button, as the screen stays ON, it also displays a visual notification.

Regards
Olivier

**Comment by di72nn** [comment]
Reopen if the issue is still reproducible with 2.4.0.
