### ISSUE TITLE
Edit saved items

### ISSUE THREAD

**Issue by Agrotsa** [wallabag/android-app#901]
Could some basic edition features be saved? Many the times we aren't really interested in keeping an entire article. Having the posibility of editing them and delete the text or images we don't need would be rather useful.

**Comment by Strubbl** [comment]
We support editing the title and the tags. Editing the content is not supported by wallabag server. Thus we cannot do this in the app and so this issue is closed.

Editing content may be better addressed at https://github.com/wallabag/wallabag/ . (IMHO this feature would be against the core idea of wallabag)

**Comment by di72nn** [comment]
// I'm pretty sure patching content through API is supported since 2.3.0.

It is hard to provide decent editing UI due to content type (HTML). So this feature is not planned.
