### ISSUE TITLE
Export from Local App Storage

### ISSUE THREAD

**Issue by brimwats** [wallabag/android-app#938]
# Issue details

### Duplicate?
no, i searched for ones. the closest was #606 which doesn't seem relavant

# Your experience with wallabag Android app

yes! it's a great app and I just want to save my data! :)

I had a docker server go very wrong, and I ended up just pulling the plug and deleting the data, getting a dedicated server. However, in that, I had accepted that I would lose my wallabag data. I opened my app today to sync it with the new server, and ! all the stuff is still there! I can even read it. Can i export the data from mobile so I can import it into my new server?

**Comment by di72nn** [comment]
I can help with export, but not necessarily with import.

So to export data from the app go to "Settings - Miscellaneous - Database location" and select "External storage", after that the DB should be available as three `wallabag*` files in `/sdcard/Android/data/fr.gaulupeau.apps.InThePoche/files/`.
You can open it with `sqlite3 wallabag` or some other SQLite-tool of your choosing.

**It is important to note that the data in the app is stored in a slightly different format than in the server:** some fields may be in a different format, some fields are missing, names are different. So you can't directly insert it on the server side. (Article content should be the same as on the server though.)

I would recommend experimenting with export/import functionality of the server. Maybe you can use the app DB to create a JSON-file to import it on the server.

**Comment by brimwats** [comment]
Ah this is great! Thank you for this. I managed to save the DB files at least and hopefully someone will come by that knows how to import, but otherwise I could just play around with it for awhile (I know basic sql). Thanks again!

**Comment by antonizoon** [comment]
I had forgotten to generate an export file before framabag.org shut down. Since I still had all my articles in the Wallabag Android App, I from its sqlite format to a Wallabag v2 compatible JSON export file.

This can be useful for others in case they lost their self hosted or cloud hosted Wallabag instance, but still have the Android app disconnected but intact.

It is crucial to generate a Wallabag v2 export JSON from the Android app before switching to a new instance, as connecting to a new instance will wipe the current Wallabag app sqlite.

https://gist.github.com/antonizoon/d8890e1fd6c9f9b524f7b8071b1d501e

**Comment by di72nn** [comment]
@antonizoon nice, thank you!
